/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : DAC.c
**     Project     : ProcessorExpert
**     Processor   : MK60FN1M0VLQ15
**     Component   : DAC_LDD
**     Version     : Component 01.081, Driver 01.08, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-08-19, 18:59, # CodeGen: 77
**     Abstract    :
**         This component implements an internal D/A converter of the MCU.
**         It contains settings for converting various format of a values
**         to supported format of the D/A converter.
**
**     Settings    :
**          Component name                                 : DAC
**          D/A converter                                  : DAC0
**          Interrupt service/event                        : Enabled
**            D/A interrupt                                : INT_DAC0
**            D/A interrupt priority                       : medium priority
**          Output pin                                     : yes
**            D/A channel (pin)                            : DAC0_OUT/CMP1_IN3/ADC0_SE23
**            D/A channel (pin) signal                     : 
**          Init value                                     : 0
**          D/A resolution                                 : 12 bits
**          Data mode                                      : unsigned 16 bits, right justified
**          Low power mode                                 : Disabled
**          Voltage reference source                       : external
**          Data buffer                                    : Enabled
**            Hardware trigger                             : Enabled
**              Source component                           : PDB
**            Work mode                                    : Normal
**            Watermark                                    : level 4
**            Buffer size                                  : 4
**              Data register 0                            : 0
**              Data register 1                            : 0
**              Data register 2                            : 0
**              Data register 3                            : 0
**          DMA                                            : Enabled
**            DMA requests                                 : 
**              Buffer start                               : Enabled
**              Buffer watermark                           : Enabled
**              Buffer end                                 : Disabled
**            DMA version                                  : Obsolete
**              DMA Transfer                               : DMATransfer
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Auto initialization                          : no
**            Event mask                                   : 
**              OnBufferWatermark                          : Disabled
**              OnBufferEnd                                : Disabled
**              OnBufferStart                              : Disabled
**              OnComplete                                 : Enabled
**              OnError                                    : Disabled
**          CPU clock/configuration selection              : 
**            Clock configuration 0                        : This component enabled
**            Clock configuration 1                        : This component disabled
**            Clock configuration 2                        : This component disabled
**            Clock configuration 3                        : This component disabled
**            Clock configuration 4                        : This component disabled
**            Clock configuration 5                        : This component disabled
**            Clock configuration 6                        : This component disabled
**            Clock configuration 7                        : This component disabled
**     Contents    :
**         Init                 - LDD_TDeviceData* DAC_Init(LDD_TUserData *UserDataPtr);
**         Enable               - LDD_TError DAC_Enable(LDD_TDeviceData *DeviceDataPtr);
**         Disable              - LDD_TError DAC_Disable(LDD_TDeviceData *DeviceDataPtr);
**         SetBuffer            - LDD_TError DAC_SetBuffer(LDD_TDeviceData *DeviceDataPtr, LDD_TData...
**         SetBufferMode        - LDD_TError DAC_SetBufferMode(LDD_TDeviceData *DeviceDataPtr,...
**         SetBufferReadPointer - LDD_TError DAC_SetBufferReadPointer(LDD_TDeviceData *DeviceDataPtr, uint8_t...
**         GetBufferReadPointer - byte DAC_GetBufferReadPointer(LDD_TDeviceData *DeviceDataPtr);
**         SetOperationMode     - LDD_TError DAC_SetOperationMode(LDD_TDeviceData *DeviceDataPtr,...
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file DAC.c
** @version 01.08
** @brief
**         This component implements an internal D/A converter of the MCU.
**         It contains settings for converting various format of a values
**         to supported format of the D/A converter.
**
*/         
/*!
**  @addtogroup DAC_module DAC module documentation
**  @{
*/         

/* MODULE DAC. */

/* {Default RTOS Adapter} No RTOS includes */
#include "Events.h"
#include "DAC.h"

#ifdef __cplusplus
extern "C" {
#endif 


typedef struct {
  bool EnUser;                         /* Enable/Disable device by user */
  LDD_TDeviceData *DmaTransferDeviceDataPtr; /* DMATransfer device data structure */
  LDD_TUserData *UserDataPtr;          /* RTOS device data structure */
} DAC_TDeviceData;                     /* Device data structure type */

/* {Default RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static DAC_TDeviceData DeviceDataPtr__DEFAULT_RTOS_ALLOC;
/*
** ===================================================================
**     Method      :  DAC_Init (component DAC_LDD)
*/
/*!
**     @brief
**         Initializes the device according to design-time
**         configuration properties. Allocates memory for the device
**         data structure. 
**         If the [Enable in init. code] is set to "yes" then the
**         device is also enabled (see the description of the Enable
**         method).
**         This method can be called only once. Before the second call
**         of Init the Deinit method must be called first. If DMA
**         service is enabled this method also initializes inherited
**         DMA Transfer component.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an events or callback parameter.
**     @return
**                         - Device data structure pointer.
*/
/* ===================================================================*/
LDD_TDeviceData* DAC_Init(LDD_TUserData *UserDataPtr)
{
  DAC_TDeviceData *DeviceDataPtr;      /* LDD device structure */
  LDD_TDeviceData *DmaTransferDeviceDataPtr; /* Auxiliary local pointer to inherited DMATransfer component LDD device structure. */
  LDD_TError Error;                    /* Auxiliary local error variable. */

  /* Allocate HAL device structure */
  /* {Default RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPtr = &DeviceDataPtr__DEFAULT_RTOS_ALLOC;
  DmaTransferDeviceDataPtr = Inhr1_Init(DeviceDataPtr); /* Initialize DMATransfer inherited component */
    if (DmaTransferDeviceDataPtr == NULL) { /* DMATransfer inherited component initialized successfully? */
      return NULL;                     /* If no, return with NULL. */
    }
      Error = Inhr1_AllocateChannel(DmaTransferDeviceDataPtr); /* Allocate DMA channel */
      Error |= Inhr1_EnableChannel(DmaTransferDeviceDataPtr); /* Enable DMA channel */
  if (Error != ERR_OK) {               /* DMA channel allocated and enabled successfully? */
   return NULL;                        /* If no, return with NULL. */
  } else {
   DeviceDataPtr->DmaTransferDeviceDataPtr = DmaTransferDeviceDataPtr; /* If yes, save pointer to DMATransfer component structure */
  }    
  DeviceDataPtr->UserDataPtr = UserDataPtr; /* Store the RTOS device structure */
  /* Enable device clock gate */
  /* SIM_SCGC2: DAC0=1 */
  SIM_SCGC2 |= SIM_SCGC2_DAC0_MASK;                                   
  DAC_PDD_EnableDevice(DAC0_BASE_PTR,PDD_DISABLE); /* Disable device */
  /* DAC0_DAT0H: ??=0,??=0,??=0,??=0,DATA=0 */
  DAC0_DAT0H = DAC_DATH_DATA(0x00);                                   
  /* DAC0_DAT0L: DATA=0 */
  DAC0_DAT0L = DAC_DATL_DATA(0x00);                                   
  /* DAC0_DAT1H: ??=0,??=0,??=0,??=0,DATA=0 */
  DAC0_DAT1H = DAC_DATH_DATA(0x00);                                   
  /* DAC0_DAT1L: DATA=0 */
  DAC0_DAT1L = DAC_DATL_DATA(0x00);                                   
  /* DAC0_DAT2H: ??=0,??=0,??=0,??=0,DATA=0 */
  DAC0_DAT2H = DAC_DATH_DATA(0x00);                                   
  /* DAC0_DAT2L: DATA=0 */
  DAC0_DAT2L = DAC_DATL_DATA(0x00);                                   
  /* DAC0_DAT3H: ??=0,??=0,??=0,??=0,DATA=0 */
  DAC0_DAT3H = DAC_DATH_DATA(0x00);                                   
  /* DAC0_DAT3L: DATA=0 */
  DAC0_DAT3L = DAC_DATL_DATA(0x00);                                   
  /* DAC0_C2: DACBFRP=0,DACBFUP=3 */
  DAC0_C2 = (DAC_C2_DACBFRP(0x00) | DAC_C2_DACBFUP(0x03));                                   
  /* DAC0_C1: DMAEN=1,??=0,??=0,DACBFWM=3,DACBFMD=0,DACBFEN=1 */
  DAC0_C1 = DAC_C1_DMAEN_MASK |
            DAC_C1_DACBFWM(0x03) |
            DAC_C1_DACBFMD(0x00) |
            DAC_C1_DACBFEN_MASK;       
  /* DAC0_SR: ??=0,??=0,??=0,??=0,??=0,DACBFWMF=0,DACBFRPTF=0,DACBFRPBF=0 */
  DAC0_SR = 0x00U;                                   
  /* DAC0_C0: DACEN=1,DACRFS=1,DACTRGSEL=0,DACSWTRG=0,LPEN=0,DACBWIEN=1,DACBTIEN=1,DACBBIEN=0 */
  DAC0_C0 = DAC_C0_DACEN_MASK |
            DAC_C0_DACRFS_MASK |
            DAC_C0_DACBWIEN_MASK |
            DAC_C0_DACBTIEN_MASK;       
  DeviceDataPtr->EnUser = TRUE;        /* Set the flag "device enabled by user" */
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_DAC_ID,DeviceDataPtr);
  return ((LDD_TDeviceData*)DeviceDataPtr); /* Return pointer to the data data structure */
}

/*
** ===================================================================
**     Method      :  DAC_Enable (component DAC_LDD)
*/
/*!
**     @brief
**         Enables DAC device. If possible, this method switches on
**         digital-to-analog converter device, voltage reference, etc.
**         This method is intended to be used together with Disable
**         method to temporary switch On/Off the device after the
**         device is initialized.
**         This method is required if the [Enable in init. code]
**         property is set to "no" value.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           - ERR_OK - OK.
**                           - ERR_SPEED - This device does not work in
**                           the active clock configuration.
*/
/* ===================================================================*/
LDD_TError DAC_Enable(LDD_TDeviceData *DeviceDataPtr)
{
  DAC_PDD_EnableDevice(DAC0_BASE_PTR,PDD_ENABLE); /* Enable device */
  ((DAC_TDeviceData*)DeviceDataPtr)->EnUser = TRUE; /* Set the flag "device enabled by user" */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  DAC_Disable (component DAC_LDD)
*/
/*!
**     @brief
**         Disables the DAC device. If possible, this method switches
**         off digital-to-analog converter device, voltage reference,
**         etc. When the device is disabled, some component methods
**         should not be called. If so, error ERR_DISABLED is reported.
**         This method is intended to be used together with Enable
**         method to temporary switch On/Off the device after the
**         device is initialized.
**         This method is not required. The Deinit method can be used
**         to switch off and uninstall the device.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           - ERR_OK - OK.
**                           - ERR_SPEED - This device does not work in
**                           the active clock configuration.
*/
/* ===================================================================*/
LDD_TError DAC_Disable(LDD_TDeviceData *DeviceDataPtr)
{
  DAC_PDD_EnableDevice(DAC0_BASE_PTR,PDD_DISABLE); /* Disable device */
  ((DAC_TDeviceData*)DeviceDataPtr)->EnUser = FALSE; /* Set the flag "device disabled by user" */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  DAC_SetBuffer (component DAC_LDD)
*/
/*!
**     @brief
**         Writes an array of data words to the data buffer registers.
**         Array is defined by pointer to start address and by it's
**         length. First written data buffer register is defined by
**         index.
**         If the length of array exceeds number of registers between
**         the first written register and the last one at the end of
**         the buffer then an ERR_PARAM_RANGE is returned and no data
**         are written. It is possible to write all register available
**         in hardware - no checking for current upper limit value of
**         buffer is done.
**         DataArrayPtr has fixed data type regardless of current
**         hardware or design time configuration and must be always
**         used. Real type of user data is specified in [Data mode]
**         property.
**         If the DMA service is enabled then this methods can be used
**         to prepare DMA transfer via channel handled by DMA Transfer
**         inherited component. 
**         _/Note: This method is available only if DAC device is
**         supporting data buffer and Data buffer is enabled./_
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         DataArrayPtr    - Pointer to array
**                           containing user data.
**     @param
**         DataArrayLength - Length of user
**                           data array which should be written to HW
**                           data buffer, immediately by this method, or
**                           by DMA after the request. 
**     @param
**         FirstRegisterIndex - Index of
**                           first written data buffer register.
**     @return
**                         - Error code, possible codes:
**                           - ERR_OK - OK.
**                           - ERR_SPEED - This device does not work in
**                           the active clock configuration.
**                           - ERR_DISABLED - Component or device is
**                           disabled.
**                           - ERR_PARAM_RANGE - Index of last written
**                           buffer register would be out of buffer
**                           range.
*/
/* ===================================================================*/
LDD_TError DAC_SetBuffer(LDD_TDeviceData *DeviceDataPtr, LDD_TData *DataArrayPtr, LDD_DAC_TArrayLength DataArrayLength, uint8_t FirstRegisterIndex)
{
  LDD_TError Error;

  /* Device state test - this test can be disabled by setting the "Ignore enable test"
     property to the "yes" value in the "Configuration inspector" */
  if (!((DAC_TDeviceData*)DeviceDataPtr)->EnUser) { /* Is device enabled? */
    return ERR_DISABLED;               /* No, return ERR_DISABLED */
  }
  Error = Inhr1_SetSourceAddress(((DAC_TDeviceData *)DeviceDataPtr)->DmaTransferDeviceDataPtr, (LDD_DMA_TAddress)DataArrayPtr);  
  Error |= Inhr1_SetDestinationAddress(((DAC_TDeviceData *)DeviceDataPtr)->DmaTransferDeviceDataPtr, (LDD_DMA_TAddress)&(DAC_DATL_REG(DAC0_BASE_PTR,FirstRegisterIndex)));
  Error |= Inhr1_SetByteCount(((DAC_TDeviceData *)DeviceDataPtr)->DmaTransferDeviceDataPtr, (LDD_DMA_TByteCount)(2U * (LDD_DMA_TByteCount)DataArrayLength));
  return Error;
}

/*
** ===================================================================
**     Method      :  DAC_SetBufferMode (component DAC_LDD)
*/
/*!
**     @brief
**         Selects buffer work mode. 
**         _/Note: This method is available only if DAC device is
**         supporting data buffer and Data buffer is enabled./_
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Mode            - Buffer work mode.
**     @return
**                         - Error code, possible codes:
**                           - ERR_OK - OK.
**                           - ERR_SPEED - This device does not work in
**                           the active clock configuration.
**                           - ERR_DISABLED - Component or device is
**                           disabled.
**                           - ERR_PARAM_MODE - Invalid mode parameter.
*/
/* ===================================================================*/
LDD_TError DAC_SetBufferMode(LDD_TDeviceData *DeviceDataPtr, LDD_DAC_TBufferMode Mode)
{
  /* Device state test - this test can be disabled by setting the "Ignore enable test"
     property to the "yes" value in the "Configuration inspector" */
  if (!((DAC_TDeviceData*)DeviceDataPtr)->EnUser) { /* Is device enabled? */
    return ERR_DISABLED;               /* No, return ERR_DISABLED */
  }
  /* Mode parameter test - this test can be disabled by setting the "Ignore range checking"
     property to the "yes" value in the "Configuration inspector" */
  if((Mode != LDD_DAC_BUFFER_NORMAL_MODE) && (Mode != LDD_DAC_BUFFER_SWING_MODE) && (Mode != LDD_DAC_BUFFER_SCAN_MODE)) { /* Is requested mode available? */
    return ERR_PARAM_MODE;             /* No, return ERR_PARAM_MODE */
  }
  DAC_PDD_SetBufferMode(DAC0_BASE_PTR,Mode);
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  DAC_SetBufferReadPointer (component DAC_LDD)
*/
/*!
**     @brief
**         Sets the data buffer read pointer value. If requested
**         pointer value is greater than buffer size defined by buffer
**         upper limit value then ERR_PARAM_VALUE is returned.
**         _/Note: This method is available only if DAC device is
**         supporting data buffer and Data buffer is enabled./_
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         PointerValue    - New read pointer value.
**     @return
**                         - Error code, possible codes:
**                           - ERR_OK - OK.
**                           - ERR_SPEED - This device does not work in
**                           the active clock configuration.
**                           - ERR_DISABLED - Component or device is
**                           disabled.
**                           - ERR_PARAM_VALUE - Invalid value parameter.
*/
/* ===================================================================*/
LDD_TError DAC_SetBufferReadPointer(LDD_TDeviceData *DeviceDataPtr, uint8_t PointerValue)
{
  /* Device state test - this test can be disabled by setting the "Ignore enable test"
     property to the "yes" value in the "Configuration inspector" */
  if (!((DAC_TDeviceData*)DeviceDataPtr)->EnUser) { /* Is device enabled? */
    return ERR_DISABLED;               /* No, return ERR_DISABLED */
  }
  /* Pointer parameter test - this test can be disabled by setting the "Ignore range checking"
     property to the "yes" value in the "Configuration inspector" */
  if(PointerValue > DAC_PDD_GetBufferSize(DAC0_BASE_PTR)) { /* Is required read pointer value in possible range? */
    return ERR_PARAM_VALUE;            /* No, return ERR_PARAM_VALUE */
  }
  DAC_PDD_SetBufferReadPointer(DAC0_BASE_PTR,PointerValue);
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  DAC_GetBufferReadPointer (component DAC_LDD)
*/
/*!
**     @brief
**         Returns the data buffer read pointer value.
**         _/Note: This method is available only if DAC device is
**         supporting data buffer and Data buffer is enabled./_
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Buffer read pointer value.
*/
/* ===================================================================*/
uint8_t DAC_GetBufferReadPointer(LDD_TDeviceData *DeviceDataPtr)
{
  (void)DeviceDataPtr;                 /* Parameter not used, suppress not used argument warning */

  return DAC_PDD_GetBufferReadPointer(DAC0_BASE_PTR);
}

/*
** ===================================================================
**     Method      :  DAC_SetOperationMode (component DAC_LDD)
*/
/*!
**     @brief
**         This method requests to change the component's operation
**         mode. Upon a request to change the operation mode, the
**         component will finish a pending job first and then notify a
**         caller that an operation mode has been changed. When no job
**         is pending (ERR_OK), the component changes an operation mode
**         immediately and notify a caller about this change. 
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         OperationMode   - Requested driver
**                           operation mode.
**     @param
**         ModeChangeCallback - Callback to
**                           notify the upper layer once a mode has been
**                           changed.
**     @param
**         ModeChangeCallbackParamPtr 
**                           - Pointer to callback parameter to notify
**                           the upper layer once a mode has been
**                           changed.
**     @return
**                         - Error code, possible codes:
**                           - ERR_OK - OK.
**                           - ERR_SPEED - This device does not work in
**                           the active clock configuration.
**                           - ERR_DISABLED - This component is disabled
**                           by user.
**                           - ERR_PARAM_MODE - Invalid operation mode.
*/
/* ===================================================================*/
LDD_TError DAC_SetOperationMode(LDD_TDeviceData *DeviceDataPtr, LDD_TDriverOperationMode OperationMode, LDD_TCallback ModeChangeCallback, LDD_TCallbackParam *ModeChangeCallbackParamPtr)
{
  /* Device state test - this test can be disabled by setting the "Ignore enable test"
     property to the "yes" value in the "Configuration inspector" */
  if (!((DAC_TDeviceData*)DeviceDataPtr)->EnUser) { /* Is device enabled? */
    return ERR_DISABLED;               /* No, return ERR_DISABLED */
  }
  switch (OperationMode) {
    case DOM_RUN:
      #if defined(SIM_PDD_CLOCK_GATE_DAC0)
      SIM_PDD_SetClockGate(SIM_BASE_PTR, SIM_PDD_CLOCK_GATE_DAC0, PDD_ENABLE);
      #endif
      DAC_PDD_SetPowerMode(DAC0_BASE_PTR, DAC_PDD_HIGH_POWER); /* Set power mode */
      if (((DAC_TDeviceData*)DeviceDataPtr)->EnUser) { /* Is device enabled by user? */
        DAC_PDD_EnableDevice(DAC0_BASE_PTR,PDD_ENABLE); /* If yes, enable device */
      }
      break;
    case DOM_WAIT:
      DAC_PDD_SetPowerMode(DAC0_BASE_PTR, DAC_PDD_LOW_POWER); /* Set low power mode */
      break;
    case DOM_SLEEP:
      DAC_PDD_SetPowerMode(DAC0_BASE_PTR, DAC_PDD_LOW_POWER); /* Set low power mode */
      DAC_PDD_EnableBuffer(DAC0_BASE_PTR, PDD_DISABLE); /* Disable buffer */
      break;
    case DOM_STOP:
      DAC_PDD_EnableDevice(DAC0_BASE_PTR,PDD_DISABLE); /* Disable device */
      #if defined(SIM_PDD_CLOCK_GATE_DAC0)
      SIM_PDD_SetClockGate(SIM_BASE_PTR, SIM_PDD_CLOCK_GATE_DAC0, PDD_DISABLE);
      #endif
      break;
    default:
      return ERR_PARAM_MODE;           /* Invalid Operation mode parameter */
  }
  if (ModeChangeCallback != NULL) {
    ModeChangeCallback(ModeChangeCallbackParamPtr); /* Invoke a callback */
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  DAC_OnComplete (component DAC_LDD)
**
**     Description :
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

void Inhr1_OnComplete(LDD_TUserData *UserDataPtr)
{
  DAC_OnComplete(((DAC_TDeviceData*)UserDataPtr)->UserDataPtr); /* Call user event */
}


/* END DAC. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
