/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : modulePIT0.c
**     Project     : ProcessorExpert
**     Processor   : MK60FN1M0VLQ15
**     Component   : Init_PIT
**     Version     : Component 01.004, Driver 01.04, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2019-08-19, 11:36, # CodeGen: 40
**     Abstract    :
**          This file implements the PIT (PIT) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : modulePIT0
**          Device                                         : PIT
**          Setttings                                      : 
**            Clock gate                                   : Enabled
**            Clock settings                               : 
**              Base clock frequency                       : 50 MHz
**            Freeze in debug mode                         : yes
**          Channels                                       : 
**            Channel 0                                    : 
**              Timer 0                                    : Enabled
**              Timer 0 load value                         : 12499
**              Timer 0 Period                             : 250 us
**              Interrupt                                  : 
**                Interrupt                                : INT_PIT0
**                Interrupt request                        : Enabled
**                Interrupt priority                       : 0 (Highest)
**                ISR Name                                 : delayInterrupt
**                Timer interrupt                          : Enabled
**            Channel 1                                    : 
**              Timer 1                                    : Disabled
**              Timer 1 load value                         : 0
**              Timer 1 Period                             : 0.020 us
**              Interrupt                                  : 
**                Interrupt                                : INT_PIT1
**                Interrupt request                        : Enabled
**                Interrupt priority                       : 0 (Highest)
**                ISR Name                                 : 
**                Timer interrupt                          : Disabled
**            Channel 2                                    : 
**              Timer 2                                    : Disabled
**              Timer 2 load value                         : 0
**              Timer 2 Period                             : 0.020 us
**              Interrupt                                  : 
**                Interrupt                                : INT_PIT2
**                Interrupt request                        : Disabled
**                Interrupt priority                       : 0 (Highest)
**                ISR Name                                 : 
**                Timer interrupt                          : Disabled
**            Channel 3                                    : 
**              Timer 3                                    : Disabled
**              Timer 3 load value                         : 0
**              Timer 3 Period                             : 0.020 us
**              Interrupt                                  : 
**                Interrupt                                : INT_PIT3
**                Interrupt request                        : Disabled
**                Interrupt priority                       : 0 (Highest)
**                ISR Name                                 : 
**                Timer interrupt                          : Disabled
**          Initialization                                 : 
**            Module                                       : Enabled
**            Call Init method                             : no
**     Contents    :
**         Init - void modulePIT0_Init(void);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file modulePIT0.c
** @version 01.04
** @brief
**          This file implements the PIT (PIT) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup modulePIT0_module modulePIT0 module documentation
**  @{
*/         

/* MODULE modulePIT0. */

#include "modulePIT0.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"


/*
** ===================================================================
**     Method      :  modulePIT0_Init (component Init_PIT)
**     Description :
**         This method initializes registers of the PIT module
**         according to the Peripheral Initialization settings.
**         Call this method in user code to initialize the module. By
**         default, the method is called by PE automatically; see "Call
**         Init method" property of the component for more details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void modulePIT0_Init(void)
{
  /* SIM_SCGC6: PIT=1 */
  SIM_SCGC6 |= SIM_SCGC6_PIT_MASK;                                   
  /* PIT_MCR: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,MDIS=0,FRZ=1 */
  PIT_MCR = PIT_MCR_FRZ_MASK;                                   
  /* PIT_TFLG0: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,TIF=1 */
  PIT_TFLG0 = PIT_TFLG_TIF_MASK;                                   
  /* PIT_TFLG1: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,TIF=1 */
  PIT_TFLG1 = PIT_TFLG_TIF_MASK;                                   
  /* PIT_TFLG2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,TIF=1 */
  PIT_TFLG2 = PIT_TFLG_TIF_MASK;                                   
  /* PIT_TFLG3: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,TIF=1 */
  PIT_TFLG3 = PIT_TFLG_TIF_MASK;                                   
  /* PIT_LDVAL0: TSV=0x30D3 */
  PIT_LDVAL0 = PIT_LDVAL_TSV(0x30D3);                                   
  /* PIT_LDVAL1: TSV=0 */
  PIT_LDVAL1 = PIT_LDVAL_TSV(0x00);                                   
  /* PIT_LDVAL2: TSV=0 */
  PIT_LDVAL2 = PIT_LDVAL_TSV(0x00);                                   
  /* PIT_LDVAL3: TSV=0 */
  PIT_LDVAL3 = PIT_LDVAL_TSV(0x00);                                   
  /* PIT_TCTRL0: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,TIE=1,TEN=0 */
  PIT_TCTRL0 = PIT_TCTRL_TIE_MASK;                                   
  /* PIT_TCTRL1: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,TIE=0,TEN=0 */
  PIT_TCTRL1 = 0x00U;                                   
  /* PIT_TCTRL2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,TIE=0,TEN=0 */
  PIT_TCTRL2 = 0x00U;                                   
  /* PIT_TCTRL3: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,TIE=0,TEN=0 */
  PIT_TCTRL3 = 0x00U;                                   
  /* PIT_TCTRL0: TEN=1 */
  PIT_TCTRL0 |= PIT_TCTRL_TEN_MASK;                                   
}

/*
** ###################################################################
**
**  The interrupt service routine(s) must be implemented
**  by user in one of the following user modules.
**
**  If the "Generate ISR" option is enabled, Processor Expert generates
**  ISR templates in the CPU event module.
**
**  User modules:
**      ProcessorExpert.c
**      Events.c
**
** ###################################################################
PE_ISR(delayInterrupt)
{
// NOTE: The routine should include actions to clear the appropriate
//       interrupt flags.
//
}
*/


/* END modulePIT0. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
